### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#262]
We are seeing intermittent test failures caused by this code:
https://github.com/extendr/extendr/blob/42d168bee850bbc3fdb3b0737832fe0f3679451d/extendr-api/tests/extendr_macro.rs#L95-L108

A comment in the code already says "They may cause stack traces, but this is harmless" but I feel this is not satisfactory. Do we understand why they sometimes fail, and is it possible to prevent this failure? Clearly the catching of R errors isn't entirely reliable as things stand right now.

**Comment by brendanrbrown** [comment]
Is this related to the intermittent failures on the windows-latest w/ bindgen tests see recently, most recently on #264?

```
Build extendr-api for stable-i686-pc-windows-gnu
ci-cargo: D:\a\_temp\6a5b1ec2-2ed6-4663-a106-cd7ee4e48881.ps1:23
Line |
  23 |    ci-cargo +$toolchain build --manifest-path extendr-api/Cargo.toml - …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'Build extendr-api for stable-i686-pc-windows-gnu': cargo failed with code 101 (args:
     | +stable-i686-pc-windows-gnu build --manifest-path extendr-api/Cargo.toml --features tests-all
     | --target=i686-pc-windows-gnu)

Error: Process completed with exit code 1.
```

**Comment by clauswilke** [comment]
No, the latest failure you pinpoint is different. I'm talking about this failure:
```
Error: Error: Expected Numeric, got String
  test tests_with_successful_outcomes ... ok
  thread 'tests_with_unsuccessful_outcomes' panicked at 'R has thrown an error.', extendr-api/src/thread_safety.rs:129:13
``` 
which you can see on Ubuntu here: https://github.com/extendr/extendr/runs/3345434167

I've also seen it happen on Windows (can't find an example right now), but it's not exclusive to Windows.

**Comment by yutannihilation** [comment]
Note that these lines are always displayed no matter the test fails or not, so it's probably not the "failure" itself.

**Comment by clauswilke** [comment]
Ah, Ok. So this is the output when everything goes well:
```
running 3 tests
  test tests_with_successful_outcomes ... ok
  Error: Error: Expected Numeric, got String
  test test_call_macro ... ok
  thread 'tests_with_unsuccessful_outcomes' panicked at 'R has thrown an error.', extendr-api/src/thread_safety.rs:129:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Error: Error: Expected Numeric, got Pairlist
  thread 'tests_with_unsuccessful_outcomes' panicked at 'R has thrown an error.', extendr-api/src/thread_safety.rs:129:13
  Error: Error: Expected Scalar, got List
  thread 'tests_with_unsuccessful_outcomes' panicked at 'R has thrown an error.', extendr-api/src/thread_safety.rs:129:13
  test tests_with_unsuccessful_outcomes ... ok
  
  test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s
```

And this is the output when something goes wrong:
```
running 3 tests
  Error: Error: Expected Numeric, got String
  test tests_with_successful_outcomes ... ok
  thread 'tests_with_unsuccessful_outcomes' panicked at 'R has thrown an error.', extendr-api/src/thread_safety.rs:129:13
  test test_call_macro ... ok
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Error: 'Testing for default target': cargo failed with code 1 (args: test  -- --nocapture)
  Error: Error: Expected Numeric, got Pairlist
Execution halted
error: test failed, to rerun pass '-p extendr-api --test extendr_macro'
ci-cargo: /home/runner/work/_temp/78c386a2-3468-4927-9a03-6ec7f75bd720.ps1:4
Line |
   4 |    ci-cargo test $(if($target -ne 'default') {"--target=$target"} ) '- …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'Testing for default target': cargo failed with code 1 (args:
     | test  -- --nocapture)

Error: Process completed with exit code 1.
```
It still suggests a problem in the code block I highlighted. We should keep an eye out for whether it's always the example with pairlist or whether any of the three lines can trigger this type of problem.

**Comment by andy-thomason** [comment]
This seems better now.

Am I safe to close this?

**Comment by clauswilke** [comment]
Yes, let's close. We can reopen if we see problems pop up again.
