### ISSUE TITLE
Add support for `...` parameter in extendr functions

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#576]
Here is a potential design of the feature:
- Introduce a parameter level attribute, similar to `#[default]`, say, `#[dotdotdot]`, or `#[ellipsis]` and allow marking (ideally, at most one) `List` parameter
- On the side of R, update wrapper generation to accept a single `...` and pass it to Rust function as `list(...)`.

**Comment by Ilia-Kosenkov** [comment]
So that
```rust
#[extendr]
fn test(x : i32, #[ellipsis] dots : List, y : i32) {}
```
should have a signature of
```R
test <- function(x, ..., y) .Call("test", x, list(...), y)
```

**Comment by Ilia-Kosenkov** [comment]
Ok, scratch that, let's do it the proper way. Here is the plan:
- `extendr-api`
  - Add new `Ellipsis` type, inspired by existing `Pairlist`
  - Teach it to be convertible from `Dot` `SEXP`
  - Create an iterator for it to traverse all of the items (check how `Pairlist` does it, unsure about names)
  - Each element of `...` is either a `Promise` or a `missing_arg`. When creating an iterator, let's return an enum of either a `Promise` or some `missing arg` so the consumer can decide how to iterate
  - Add a simple method to `Ellipsis`, let's call it `materialize(&self) -> Iter<Robj>` -- call iterator created above, `filter_map` on `Promise::try_from()` to get only valid promises, then evaluate them with `.then(|p| p.evaluate())` (should we also include names if any?)
  - Update `TryFrom<Robj> for Ellipsis`, allow accepting an `Environment`, then use `.find()` to find an item named `"..."`. If found and of type `Dot`, create an `Ellipsis` from it.

- Likely `extendr-macros`
  - Update wrapper generation
    - Rename the parameter to `...` on R side if type is `Ellipsis`
    - Instead of passing `...`, pass `environment()` in the place of `Ellipsis` arg in `.Call()`

**Comment by Ilia-Kosenkov** [comment]
So I have a working prototype:
``` r
local_extendr_api <- "...\\extendr\\extendr-api"

rextendr::rust_function(
    "fn test(mandatory_arg : String, #[ellipsis]dots : Ellipsis, last_arg : i32) -> Result<List> {
        rprintln!(\"First arg is {:?}\", &mandatory_arg);
        rprintln!(\"Last arg is {:?}\", &last_arg);
        dots.values().map(|v| List::from_pairs(v))
    }",
    extendr_deps = list(`extendr-api` = list(path = local_extendr_api)),
    extendr_fn_options = list(use_try_from = TRUE)
)
#> ℹ build directory: 'C:/Users/.../AppData/Local/Temp/RtmpuUPEXU/filea27c289e6999'
#> ✔ Writing 'C:/Users/.../AppData/Local/Temp/RtmpuUPEXU/filea27c289e6999/target/extendr_wrappers.R'

test |> print()
#> function(mandatory_arg, ..., last_arg) .Call("wrap__test", mandatory_arg, environment(), last_arg, PACKAGE = "rextendr1")

test("Hello World!", 1, 2, 3, last_arg = 42, `4` = 4, ) # Missing arg at the end is OK
#> First arg is "Hello World!"
#> Last arg is 42
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 2
#> 
#> [[3]]
#> [1] 3
#> 
#> $`4`
#> [1] 4

test("Hello World!", 1, 2, ,3, last_arg = 42) # Missing arg fails
#> First arg is "Hello World!"
#> Last arg is 42
#> Error in test("Hello World!", 1, 2, , 3, last_arg = 42): user function panicked: test
```

<sup>Created on 2023-07-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


The current error is a bit ugly:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Other("Missing value for [3] element")', ...\extendr\extendr-api\src\robj\into_robj.rs:49:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'explicit panic', src\lib.rs:2:1
Error in test("Hello World!", 1, 2, , 3, last_arg = 42) :
  user function panicked: test
```
